version: '2'

networks:
  fabric:
    external:
      name: net_basic

services:
  bc-api:
    container_name: bc-api
    build: 
      context: .
      dockerfile: dockerfile
    command: 'node index.js'
    volumes:
      - /home/huma/fabric-course/api:/usr/src/app
    ports:
      - 80:3000
    networks:
      - fabric
